version: '3.8'

services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn src.router:app --host 0.0.0.0'
    ports:
      - 8008:8000
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - ./sql_quires:/docker-entrypoint-initdb.d
      - ${PATH_TO_DB_DATA}:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}